apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: jeremiahbuckley-t2-poi-backend-app-dev
  annotations:
    argocd/app-name: jeremiahbuckley-t2-poi-backend-app-dev
    backstage.io/kubernetes-id: jeremiahbuckley-t2-poi-backend-app
    backstage.io/kubernetes-namespace: jeremiahbuckley-t2
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: rhdh-ms/jeremiahbuckley-t2-backend
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - java
    - quarkus
    - maven
    - workshop
  links:
    - url: https://console-openshift-console.apps.igb2792k.eastus2.aroapp.io/dev-pipelines/ns/jeremiahbuckley-t2/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.igb2792k.eastus2.aroapp.io/k8s/ns/jeremiahbuckley-t2/deployments/jeremiahbuckley-t2-poi-backend-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.igb2792k.eastus2.aroapp.io/#https://github.com/rhdh-ms/jeremiahbuckley-t2-backend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/jeremiahbuckley"
  system: workshop-system-jeremiahbuckley-t2
  providesApis:
    - backend-api-jeremiahbuckley-t2
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-jeremiahbuckley-t2
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:default/jeremiahbuckley"
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: backend-api-jeremiahbuckley-t2
  description: API surface used by workshop attendees to initialize and load parks data
  links:
    - url: http://jeremiahbuckley-t2-poi-backend-app-jeremiahbuckley-t2.apps.igb2792k.eastus2.aroapp.io/q/swagger-ui
      title: Swagger UI
      icon: web
    - url: https://github.com/rhdh-ms/jeremiahbuckley-t2-backend/tree/main/src/main/resources/META-INF/openapi.yaml
      title: API Spec
      icon: code
spec:
  type: openapi
  lifecycle: production
  owner: "user:default/jeremiahbuckley"
  system: workshop-system-jeremiahbuckley-t2
  definition:
    $text: https://github.com/rhdh-ms/jeremiahbuckley-t2-backend/tree/main/src/main/resources/META-INF/openapi.yaml
